name: Second workflow
on:
  push:
    branches:
        - "main"
jobs:
    unittest: 
        name: Unit Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Checkout
            - uses: actions/setup-go@v3
              name: Setup Go environment
              with:
                go-version-file: ./src/go.mod
            - name: Run Unit Test
              working-directory: ./src
              run: go test ./...
